name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true
      title:
        description: 'Title of the release'
        required: true

permissions:
  contents: write

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Release Description from Markdown File
        run: |
          description=$(<"release.md")
          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$description" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESCRIPTION: ${{ env.DESCRIPTION }}
        run: |
          tag="${{ github.event.inputs.tag }}"
          title="${{ github.event.inputs.title }}"
          description="$DESCRIPTION"

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg tag "$tag" --arg title "$title" --arg description "$description" \
                '{tag_name: $tag, target_commitish: "main", name: $title, body: $description, draft: false, prerelease: false}')" \
            https://api.github.com/repos/JEMcats/windingtrailsdigitalmap/releases \
            --output release.json

          upload_url=$(jq -r '.upload_url' release.json | sed "s/{?name,label}//")
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV

      - name: Upload data.json to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ env.UPLOAD_URL }}
          TITLE: ${{ github.event.inputs.title }}
        run: |
          upload_url="${UPLOAD_URL}?name=data-${TITLE}.json"
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @./assets/data.json \
            "$upload_url"

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync . s3://jemcats.software/websites/windingtrailsdigitalmap/ \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore" \
            --exclude "release.md" \
            --exclude "assets/tiles.zip" \
            --exclude "assets/note.txt" \
            --exclude "README.md" \
            --exclude "awscliv2.zip" \
            --exclude "aws/*"